# Generated by Django 4.2.25 on 2026-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_relax_legacy_account_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
