# Generated by Django 4.2.25 on 2026-05-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_employeeprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
