# Generated by Django 4.2.25 on 2026-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_teammember_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='mobile', max_length=500),
        ),
    ]
