# Generated by Django 3.2.7 on 2026-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_project_category_multichoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text="Show this service in the Home Page 'What We Do' section"),
        ),
    ]
