# Generated by Django 3.2.7 on 2026-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_service_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text="Show this product in the Home Page 'Our Products' section"),
        ),
    ]
