# Generated by Django 3.2.7 on 2026-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_companycertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='companycertificate',
            name='validity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
