# Generated by Django 3.2.7 on 2026-07-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_auto_20260630_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_booklet',
            field=models.FileField(blank=True, help_text='Optional PDF booklet for the project (stored in DigitalOcean Spaces / CDN).', null=True, upload_to='project-pdfs/'),
        ),
    ]
