# Generated by Django 3.2.7 on 2026-07-14 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_project_pdf_booklet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSolution',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='IT-solutions/')),
                ('long_description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('use_cases', models.JSONField(blank=True, default=list)),
                ('explore', models.JSONField(blank=True, default=dict)),
                ('demo_video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='it_solutions', to='account.TeamMember')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
