# Generated by Django 3.2.7 on 2026-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_itsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsolution',
            name='pdf_booklet',
            field=models.FileField(blank=True, help_text='Optional PDF booklet for the solution (stored in DigitalOcean Spaces / CDN).', null=True, upload_to='solution-pdfs/'),
        ),
        migrations.AddField(
            model_name='service',
            name='pdf_booklet',
            field=models.FileField(blank=True, help_text='Optional PDF booklet for the service (stored in DigitalOcean Spaces / CDN).', null=True, upload_to='service-pdfs/'),
        ),
    ]
