# Generated by Django 3.2.7 on 2026-07-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_auto_20260714_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisservice',
            name='pdf_booklet',
            field=models.FileField(blank=True, help_text='Optional PDF booklet for the GIS service (stored in DigitalOcean Spaces / CDN).', null=True, upload_to='gisservice-pdfs/'),
        ),
    ]
