# Generated by Django 3.2.7 on 2026-07-21 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_contactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_type', models.CharField(choices=[('employment', 'Employment Certificate'), ('experience', 'Experience Certificate'), ('internship', 'Internship Completion'), ('training', 'Training Certificate'), ('appreciation', 'Appreciation Certificate'), ('promotion', 'Promotion Certificate'), ('custom', 'Custom Certificate')], default='employment', max_length=30)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='certificate-signatures/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='certificate-stamps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_certificates', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='account.employeeprofile')),
            ],
        ),
    ]
