# Generated by Django 3.2.7 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_employeecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertificate',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
