# Generated by Django 3.2.7 on 2026-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_employeecertificate_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertificate',
            name='internship_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecertificate',
            name='internship_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
