# Generated by Django 3.2.7 on 2026-07-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_employeecertificate_internship_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('employment', 'Employment Certificate'), ('experience', 'Experience Certificate'), ('internship', 'Internship Completion'), ('relieving', 'Relieving Certificate'), ('training', 'Training Certificate'), ('appreciation', 'Appreciation Certificate'), ('promotion', 'Promotion Certificate'), ('custom', 'Custom Certificate')], default='employment', max_length=30),
        ),
    ]
