# Generated by Django 3.2.7 on 2026-08-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_alter_employeecertificate_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Hero background image for project detail page', null=True, upload_to='project-banners/'),
        ),
        migrations.AlterField(
            model_name='employeecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('employment', 'Employment Certificate'), ('experience', 'Experience Certificate'), ('internship', 'Internship Completion'), ('relieving', 'Relieving Letter'), ('training', 'Training Certificate'), ('appreciation', 'Appreciation Certificate'), ('promotion', 'Promotion Certificate'), ('custom', 'Custom Certificate')], default='employment', max_length=30),
        ),
    ]
