# Generated by Django 3.2.7 on 2026-09-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_employeeticket_assignees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeticket',
            options={'ordering': ['-updated_at', '-id']},
        ),
    ]
