# Generated by Django 3.2.7 on 2026-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_alter_employeeticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeticketcomment',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
