# Generated by Django 3.2.7 on 2026-10-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_employeeticketcomment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeticketcomment',
            name='updated_at',
        ),
    ]
