# Generated by Django 3.2.7 on 2026-10-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_remove_employeeticketcomment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeticketcomment',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
