# Generated by Django 4.2.25 on 2026-05-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='DiracAI', help_text='Company name shown in the top navbar logo.', max_length=100)),
                ('hero_heading', models.CharField(default='Your Vision, Our', help_text='First part of the large hero headline.', max_length=200)),
                ('hero_highlight', models.CharField(default='Technology', help_text='The gradient-coloured word in the hero headline.', max_length=100)),
                ('hero_subheading', models.TextField(default='From Vision to Reality With AI-Driven IT Services', help_text='Descriptive line below the main headline.')),
                ('hero_video', models.FileField(blank=True, help_text='Background video for the hero section. Stored in DigitalOcean Spaces.', null=True, upload_to='hero-videos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
