# Generated by Django 4.2.25 on 2026-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Video file stored in DigitalOcean Spaces.', upload_to='hero-videos/')),
                ('title', models.CharField(blank=True, default='', help_text='Optional label (shown in admin only).', max_length=100)),
                ('duration', models.PositiveIntegerField(default=8, help_text='Seconds this clip plays before switching to the next.')),
                ('is_selected', models.BooleanField(default=False, help_text='Include this video in the homepage slideshow.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position in the slideshow (lower = earlier).')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Video',
                'verbose_name_plural': 'Hero Videos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
