# Generated by Django 4.2.25 on 2026-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='image',
            field=models.FileField(blank=True, help_text='Image file stored in DigitalOcean Spaces.', null=True, upload_to='hero-images/'),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', help_text='Type of media: video or image.', max_length=10),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video',
            field=models.FileField(blank=True, help_text='Video file stored in DigitalOcean Spaces.', null=True, upload_to='hero-videos/'),
        ),
    ]
