# Generated by Django 3.2.7 on 2026-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_herovideo_image_herovideo_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='heading',
            field=models.TextField(blank=True, default='', help_text='Main custom heading for this specific slide. Supports multiple lines.'),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='subheading',
            field=models.TextField(blank=True, default='', help_text='Custom subheading for this specific slide. Supports multiple lines.'),
        ),
    ]
