# Generated by Django 3.2.7 on 2026-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20260630_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='button_link',
            field=models.CharField(blank=True, default='', help_text='URL or path for the action button to link to.', max_length=255),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='button_text',
            field=models.CharField(blank=True, default='', help_text='Text for the action button (e.g., "Learn More").', max_length=50),
        ),
    ]
